"""Create a PR with generated spec and tests via gh CLI."""

import subprocess
import sys
from pathlib import Path
from spec_verify.runner import AnalysisResult


def create_spec_pr(source_path: Path, function_name: str, result: AnalysisResult) -> str:
    """Create a branch, commit spec+tests, and create a PR via gh."""

    branch = f"spec/{function_name}"
    _run(["git", "checkout", "-b", branch])

    # Write spec into source file (as a comment before the function)
    # For now, write spec and tests as separate files
    spec_file = Path(f"specs/{function_name}.gherkin")
    spec_file.parent.mkdir(parents=True, exist_ok=True)
    spec_file.write_text(result.spec)

    test_file = Path(f"tests/unit/src/test_{function_name}.c")
    test_file.parent.mkdir(parents=True, exist_ok=True)
    test_file.write_text(result.tests)

    _run(["git", "add", str(spec_file), str(test_file)])
    _run(["git", "commit", "-m", f"feat: add spec and tests for {function_name}()"])
    _run(["git", "push", "-u", "origin", branch])

    pr_result = _run(
        ["gh", "pr", "create",
         "--base", "develop",
         "--title", f"Add spec + tests for {function_name}()",
         "--body", f"Auto-generated by spec-verify.\n\n## Spec\n```gherkin\n{result.spec}\n```"],
        capture=True,
    )
    return pr_result.stdout.strip()


def _run(cmd: list[str], capture: bool = False) -> subprocess.CompletedProcess:
    result = subprocess.run(
        cmd,
        capture_output=capture,
        text=True,
    )
    if result.returncode != 0:
        print(f"Command failed: {' '.join(cmd)}", file=sys.stderr)
        if capture:
            print(result.stderr, file=sys.stderr)
        raise SystemExit(1)
    return result
